# Generated by Django 5.2.4 on 2025-07-21 09:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('legal_name', models.CharField(max_length=128, null=True, unique=True)),
                ('e_mail', models.CharField(max_length=254, null=True)),
                ('website', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('category', models.CharField(choices=[('supplied', 'Tedarik'), ('cardboard', 'Koli/Karton'), ('part', 'Parça/Yarı-mamul'), ('good', 'Satılabilir ürün'), ('administrative', 'İdari malzeme'), ('pallet', 'palet'), ('undefined', 'Belirtilmemiş')], default='undefined', max_length=32)),
                ('internal_code', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('role', models.CharField(choices=[('owner', 'Firma sahibi'), ('employee', 'Çalışan'), ('salesperson', 'Satış temsilcisi'), ('procurement', 'Satın almacı')], max_length=32, null=True)),
                ('e_mail', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('description', models.TextField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('legal_name', models.CharField(db_index=True, max_length=128, null=True)),
                ('e_mail', models.CharField(max_length=254, null=True)),
                ('website', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('description', models.TextField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical company',
                'verbose_name_plural': 'historical companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('role', models.CharField(choices=[('owner', 'Firma sahibi'), ('employee', 'Çalışan'), ('salesperson', 'Satış temsilcisi'), ('procurement', 'Satın almacı')], max_length=32, null=True)),
                ('e_mail', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('description', models.TextField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact',
                'verbose_name_plural': 'historical contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('category', models.CharField(choices=[('supplied', 'Tedarik'), ('cardboard', 'Koli/Karton'), ('part', 'Parça/Yarı-mamul'), ('good', 'Satılabilir ürün'), ('administrative', 'İdari malzeme'), ('pallet', 'palet'), ('undefined', 'Belirtilmemiş')], default='undefined', max_length=32)),
                ('internal_code', models.CharField(blank=True, db_index=True, max_length=14, null=True)),
                ('description', models.TextField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical material',
                'verbose_name_plural': 'historical materials',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
