# Generated by Django 5.2.4 on 2025-07-21 10:06

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=core.fields.GenderField(choices=[('e', 'Erkek'), ('k', 'Kadın'), ('b', 'Belirtilmedi')], default='b', max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='gender',
            field=core.fields.GenderField(choices=[('e', 'Erkek'), ('k', 'Kadın'), ('b', 'Belirtilmedi')], default='b', max_length=1, verbose_name='Cinsiyet'),
        ),
    ]
