# Generated by Django 5.2.4 on 2025-07-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalmaterial_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='company',
            name='e_mail',
            field=models.CharField(max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Ticari Unvan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=254, null=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='e_mail',
            field=models.CharField(max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('owner', 'Firma sahibi'), ('employee', 'Çalışan'), ('salesperson', 'Satış temsilcisi'), ('procurement', 'Satın almacı')], max_length=32, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='e_mail',
            field=models.CharField(max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='legal_name',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='Ticari Unvan'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='website',
            field=models.CharField(max_length=254, null=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='e_mail',
            field=models.CharField(max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(choices=[('owner', 'Firma sahibi'), ('employee', 'Çalışan'), ('salesperson', 'Satış temsilcisi'), ('procurement', 'Satın almacı')], max_length=32, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='category',
            field=models.CharField(choices=[('supplied', 'Tedarik'), ('cardboard', 'Koli/Karton'), ('part', 'Parça/Yarı-mamul'), ('good', 'Satılabilir ürün'), ('administrative', 'İdari malzeme'), ('pallet', 'palet'), ('undefined', 'Belirtilmemiş')], default='undefined', max_length=32, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='internal_code',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='İç Kod'),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('supplied', 'Tedarik'), ('cardboard', 'Koli/Karton'), ('part', 'Parça/Yarı-mamul'), ('good', 'Satılabilir ürün'), ('administrative', 'İdari malzeme'), ('pallet', 'palet'), ('undefined', 'Belirtilmemiş')], default='undefined', max_length=32, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='material',
            name='internal_code',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='İç Kod'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Ad'),
        ),
    ]
