# Generated by Django 5.2.4 on 2025-07-28 08:43

import core.fields
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('account_code', models.CharField(max_length=20, unique=True, verbose_name='Hesap Kodu')),
                ('account_name', models.CharField(max_length=128, verbose_name='Hesap Adı')),
                ('account_type', models.CharField(choices=[('asset', 'Varlık'), ('liability', 'Yükümlülük'), ('equity', 'Özkaynak'), ('revenue', 'Gelir'), ('expense', 'Gider')], max_length=20, verbose_name='Hesap Türü')),
                ('account_category', models.CharField(choices=[('current_assets', 'Dönen Varlıklar'), ('accounts_receivable', 'Alacaklar'), ('inventory', 'Stok'), ('accounts_payable', 'Borçlar'), ('revenue', 'Satış Gelirleri'), ('cogs', 'Satışların Maliyeti')], max_length=20, verbose_name='Hesap Kategorisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Açıklama')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='finance.account', verbose_name='Üst Hesap')),
            ],
            options={
                'verbose_name': 'Hesap',
                'verbose_name_plural': 'Hesaplar',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('movement_type', models.CharField(choices=[('debit', 'Borç'), ('credit', 'Alacak')], max_length=10, verbose_name='Hareket Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tutar')),
                ('description', models.TextField(max_length=500, verbose_name='Açıklama')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.account', verbose_name='Hesap')),
            ],
            options={
                'verbose_name': 'Hesap Hareketi',
                'verbose_name_plural': 'Hesap Hareketleri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('from_currency', core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6, verbose_name='Kaynak Para Birimi')),
                ('to_currency', core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6, verbose_name='Hedef Para Birimi')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Kur')),
            ],
            options={
                'verbose_name': 'Döviz Kuru',
                'verbose_name_plural': 'Döviz Kurları',
                'ordering': ['-date', 'from_currency', 'to_currency'],
                'indexes': [models.Index(fields=['date'], name='finance_cur_date_81df14_idx'), models.Index(fields=['from_currency', 'to_currency'], name='finance_cur_from_cu_db315b_idx'), models.Index(fields=['date', 'from_currency', 'to_currency'], name='finance_cur_date_e5313e_idx')],
                'unique_together': {('date', 'from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('account_code', models.CharField(db_index=True, max_length=20, verbose_name='Hesap Kodu')),
                ('account_name', models.CharField(max_length=128, verbose_name='Hesap Adı')),
                ('account_type', models.CharField(choices=[('asset', 'Varlık'), ('liability', 'Yükümlülük'), ('equity', 'Özkaynak'), ('revenue', 'Gelir'), ('expense', 'Gider')], max_length=20, verbose_name='Hesap Türü')),
                ('account_category', models.CharField(choices=[('current_assets', 'Dönen Varlıklar'), ('accounts_receivable', 'Alacaklar'), ('inventory', 'Stok'), ('accounts_payable', 'Borçlar'), ('revenue', 'Satış Gelirleri'), ('cogs', 'Satışların Maliyeti')], max_length=20, verbose_name='Hesap Kategorisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Açıklama')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account', verbose_name='Üst Hesap')),
            ],
            options={
                'verbose_name': 'historical Hesap',
                'verbose_name_plural': 'historical Hesaplar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccountMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('movement_type', models.CharField(choices=[('debit', 'Borç'), ('credit', 'Alacak')], max_length=10, verbose_name='Hareket Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tutar')),
                ('description', models.TextField(max_length=500, verbose_name='Açıklama')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account', verbose_name='Hesap')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Hesap Hareketi',
                'verbose_name_plural': 'historical Hesap Hareketleri',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_code'], name='finance_acc_account_1ff24b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='finance_acc_account_3b66f3_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='finance_acc_is_acti_4329a8_idx'),
        ),
    ]
