# Generated by Django 5.2.4 on 2025-07-28 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmovement',
            name='currency',
            field=core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalaccountmovement',
            name='currency',
            field=core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6),
        ),
    ]
