# Generated by Django 5.2.4 on 2025-07-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorylocation',
            unique_together={('facility', 'area', 'section', 'shelf', 'bin')},
        ),
    ]
