# Generated by Django 5.2.4 on 2025-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorylocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylocation',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Yüksekliği (cm)'),
        ),
    ]
