# Generated by Django 5.2.4 on 2025-07-23 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
        ('inventory', '0003_inventorylocation_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalInventory',
            new_name='HistoricalStockRecord',
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='StockRecord',
        ),
        migrations.AlterModelOptions(
            name='historicalstockrecord',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stock record', 'verbose_name_plural': 'historical stock records'},
        ),
    ]
