# Generated by Django 5.2.4 on 2025-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalstockrecord_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylocation',
            name='depth',
            field=models.IntegerField(null=True, verbose_name='Derinlik (cm)'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Yüksekliği (cm)'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='width',
            field=models.IntegerField(null=True, verbose_name='Genişliği (cm)'),
        ),
    ]
