# Generated by Django 5.2.4 on 2025-07-23 12:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorylocation_depth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='İsim')),
                ('facility', models.CharField(choices=[('esenyurt', 'Esenyurt')], default='esenyurt', max_length=50, verbose_name='Tesis')),
                ('area', models.IntegerField(null=True, verbose_name='Bölge')),
                ('section', models.IntegerField(null=True, verbose_name='Sıra')),
                ('shelf', models.IntegerField(null=True, verbose_name='Raf')),
                ('bin', models.IntegerField(null=True, verbose_name='Bölme')),
                ('type', models.CharField(choices=[('industrial_shelf', 'Raf'), ('exit_transit', 'Sevk transit'), ('injection_transit', 'Enjeksiyondan depoya'), ('manufacturing_transit', 'Montajdan depoya'), ('resin_storage', 'Plastik hammadde'), ('masterbatch', 'Masterbatch'), ('chemical', 'Kimyasal'), ('unlabeled', 'Bildirilmemiş'), ('temporary', 'Geçici')], default='unlabeled', max_length=50, verbose_name='Tipi')),
                ('width', models.IntegerField(null=True, verbose_name='Genişliği (cm)')),
                ('height', models.IntegerField(null=True, verbose_name='Yüksekliği (cm)')),
                ('depth', models.IntegerField(null=True, verbose_name='Derinlik (cm)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inventory location',
                'verbose_name_plural': 'historical inventory locations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
