# Generated by Django 5.2.4 on 2025-07-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalinventorylocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'permissions': [('transact_stockrecord', 'Enter/exit stock')]},
        ),
    ]
