# Generated by Django 5.2.4 on 2025-07-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'permissions': [('transact_stockrecord', 'Enter/exit stock, see incoming')]},
        ),
    ]
