# Generated by Django 5.2.4 on 2025-07-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'permissions': [('transact_stockrecord', 'Enter/exit stock, see incoming and exits')]},
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
    ]
