# Generated by Django 5.2.4 on 2025-08-01 09:50

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
        ('inventory', '0011_remove_stockrecord_location_and_more'),
        ('procurement', '0018_historicalprocurementorder_invoice_number_and_more'),
        ('sales', '0006_historicalsalesorderline_line_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Miktar')),
                ('uom', core.fields.UOMField(choices=[('ADT', 'Adet'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Mililitre'), ('M', 'Metre'), ('BOX', 'Koli'), ('PLT', 'Palet')], default='ADT', max_length=4, verbose_name='Birim')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Malzeme')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', core.fields.UOMField(choices=[('ADT', 'Adet'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Mililitre'), ('M', 'Metre'), ('BOX', 'Koli'), ('PLT', 'Palet')], default='ADT', max_length=4, verbose_name='Birim')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Miktar')),
                ('action', models.CharField(choices=[('IN', 'Depoya giriş'), ('OUT', 'Depodan çıkış'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer'), ('MO_IN', 'Üretimden gelen'), ('MO_UT', 'Üretime giden')], max_length=16, verbose_name='Eylem')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Birim fiyat')),
                ('reason', models.TextField(verbose_name='Gerekçe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation', verbose_name='Konum')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Malzeme')),
                ('po_line', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.procurementorder', verbose_name='PO#')),
                ('so_line', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder', verbose_name='SO#')),
            ],
            options={
                'verbose_name': 'Stock Record',
                'verbose_name_plural': 'Stock Records',
                'permissions': [('transact_stockrecord', 'Enter/exit stock, see incoming and exits')],
            },
        ),
    ]
