# Generated by Django 5.2.4 on 2025-08-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventorybalance_stockmovement'),
        ('procurement', '0019_alter_historicalprocurementorder_due_in_days_and_more'),
        ('sales', '0006_historicalsalesorderline_line_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='po_line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.procurementorderline', verbose_name='PO#'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='so_line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesorderline', verbose_name='SO#'),
        ),
    ]
