# Generated by Django 5.2.4 on 2025-07-28 11:43

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='uom',
            field=core.fields.UOMField(choices=[('ADT', 'Adet'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Mililitre'), ('M', 'Metre'), ('BOX', 'Koli'), ('PLT', 'Palet')], default=None, max_length=4, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='historicalbom',
            name='uom',
            field=core.fields.UOMField(choices=[('ADT', 'Adet'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Mililitre'), ('M', 'Metre'), ('BOX', 'Koli'), ('PLT', 'Palet')], default=None, max_length=4, verbose_name='Birim'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'uom')},
        ),
        migrations.AlterUniqueTogether(
            name='bomline',
            unique_together={('bom', 'component', 'uom')},
        ),
    ]
