# Generated by Django 5.2.4 on 2025-07-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprocurementorderline',
            old_name='quantity',
            new_name='uom',
        ),
        migrations.RenameField(
            model_name='procurementorderline',
            old_name='quantity',
            new_name='uom',
        ),
    ]
