# Generated by Django 5.2.4 on 2025-07-21 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_rename_quantity_historicalprocurementorderline_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocurementorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
