# Generated by Django 5.2.4 on 2025-07-21 19:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_description_alter_company_e_mail_and_more'),
        ('procurement', '0004_historicalprocurementorderline_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterialdemand',
            name='deadline',
            field=models.DateField(verbose_name='Son Tarih'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialdemand',
            name='demand_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Talep No'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialdemand',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialdemand',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.material', verbose_name='Malzeme'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialdemand',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialdemand',
            name='status',
            field=models.CharField(choices=[('submitted', 'Gönderildi'), ('approved', 'Onaylandı'), ('closed', 'Kapandı')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='delivery_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Teslimat Adresi'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='due_discount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vade İskontosu'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='due_discount_days',
            field=models.DurationField(verbose_name='Vade İskonto Günü'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='due_in_days',
            field=models.DurationField(verbose_name='Vade Günü'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='invoice_accepted',
            field=models.DateField(verbose_name='Fatura Kabul Tarihi'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('ordered', 'Sipariş verildi'), ('billed', 'Faturalandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='trade_discount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ticari İskonto'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company', verbose_name='Tedarikçi'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.material', verbose_name='Malzeme'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='po',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.procurementorder', verbose_name='Satınalma Siparişi'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Alınan Miktar'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vergi Oranı'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='deadline',
            field=models.DateField(verbose_name='Son Tarih'),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='demand_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Talep No'),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='core.material', verbose_name='Malzeme'),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='materialdemand',
            name='status',
            field=models.CharField(choices=[('submitted', 'Gönderildi'), ('approved', 'Onaylandı'), ('closed', 'Kapandı')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='procurementinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, verbose_name='Fatura No'),
        ),
        migrations.AlterField(
            model_name='procurementinvoice',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='procurement.procurementorder', verbose_name='Satınalma Siparişi'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='delivery_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Teslimat Adresi'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='due_discount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vade İskontosu'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='due_discount_days',
            field=models.DurationField(verbose_name='Vade İskonto Günü'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='due_in_days',
            field=models.DurationField(verbose_name='Vade Günü'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='invoice_accepted',
            field=models.DateField(verbose_name='Fatura Kabul Tarihi'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('ordered', 'Sipariş verildi'), ('billed', 'Faturalandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='trade_discount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ticari İskonto'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Tedarikçi'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Malzeme'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.procurementorder', verbose_name='Satınalma Siparişi'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Alınan Miktar'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vergi Oranı'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Birim Fiyat'),
        ),
    ]
