# Generated by Django 5.2.4 on 2025-07-21 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_historicalmaterialdemand_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Birim Fiyat'),
        ),
    ]
