# Generated by Django 5.2.4 on 2025-07-21 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_historicalprocurementorderline_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Sunuldu'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('ordered', 'Sipariş verildi'), ('billed', 'Faturalandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Alınan Miktar'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vergi Oranı'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Sunuldu'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('ordered', 'Sipariş verildi'), ('billed', 'Faturalandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Alınan Miktar'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vergi Oranı'),
        ),
        migrations.AlterField(
            model_name='procurementorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birim Fiyat'),
        ),
    ]
