# Generated by Django 5.2.4 on 2025-07-22 06:08


from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_historicalprocurementorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocurementorder',
            name='invoice_accepted',
        ),
        migrations.RemoveField(
            model_name='procurementorder',
            name='invoice_accepted',
        ),
        migrations.AddField(
            model_name='historicalprocurementorder',
            name='invoice_date',
            field=models.DateField(default=date(2025, 7, 22), verbose_name='Fatura Tebliğ Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='invoice_date',
            field=models.DateField(default=date(2025, 7, 22), verbose_name='Fatura Tebliğ Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='incoterms',
            field=models.CharField(choices=[('EXW', 'İşyerinde Teslim (EXW)'), ('FCA', 'Taşıyıcıya Teslim (FCA)'), ('FAS', 'Gemi Yanında Teslim (FAS)'), ('FOB', 'Gemiye Teslim (FOB)'), ('CFR', 'Navlun Dahil Teslim (CFR)'), ('CIF', 'Navlun ve Sigorta Dahil Teslim (CIF)'), ('CPT', 'Taşıma Ücreti Ödenmiş Teslim (CPT)'), ('CIP', 'Taşıma ve Sigorta Ücreti Ödenmiş Teslim (CIP)'), ('DAP', 'Varış Yerinde Teslim (DAP)'), ('DPU', 'Boşaltılmış Teslim (DPU)'), ('DDP', 'Gümrük Vergisi Ödenmiş Teslim (DDP)')], max_length=20, verbose_name='Teslim Şekli (Incoterms)'),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='payment_term',
            field=models.CharField(choices=[('NET_T', 'Net Vade'), ('DUE_ON_RECEIPT', 'Teslimde Ödeme'), ('CIA', 'Peşin Ödeme'), ('CWO', 'Siparişle Birlikte Ödeme'), ('COD', 'Teslimde Nakit'), ('CAD', 'Belge Karşılığı Ödeme'), ('EOM', 'Ay Sonu'), ('T_EOM', 'Ay sonundan T gün sonra'), ('PROX', 'Proksimo'), ('PARTIAL_ADVANCE', 'Kısmi Peşin Ödeme'), ('LC', 'Akreditif'), ('DC', 'Belge Tahsilatı'), ('X_Y_NET_T', 'X/Y Net Vade'), ('TRADE_DISCOUNT', 'Ticari İskonto')], max_length=20, verbose_name='Vade Şartı'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='incoterms',
            field=models.CharField(choices=[('EXW', 'İşyerinde Teslim (EXW)'), ('FCA', 'Taşıyıcıya Teslim (FCA)'), ('FAS', 'Gemi Yanında Teslim (FAS)'), ('FOB', 'Gemiye Teslim (FOB)'), ('CFR', 'Navlun Dahil Teslim (CFR)'), ('CIF', 'Navlun ve Sigorta Dahil Teslim (CIF)'), ('CPT', 'Taşıma Ücreti Ödenmiş Teslim (CPT)'), ('CIP', 'Taşıma ve Sigorta Ücreti Ödenmiş Teslim (CIP)'), ('DAP', 'Varış Yerinde Teslim (DAP)'), ('DPU', 'Boşaltılmış Teslim (DPU)'), ('DDP', 'Gümrük Vergisi Ödenmiş Teslim (DDP)')], max_length=20, verbose_name='Teslim Şekli (Incoterms)'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='payment_term',
            field=models.CharField(choices=[('NET_T', 'Net Vade'), ('DUE_ON_RECEIPT', 'Teslimde Ödeme'), ('CIA', 'Peşin Ödeme'), ('CWO', 'Siparişle Birlikte Ödeme'), ('COD', 'Teslimde Nakit'), ('CAD', 'Belge Karşılığı Ödeme'), ('EOM', 'Ay Sonu'), ('T_EOM', 'Ay sonundan T gün sonra'), ('PROX', 'Proksimo'), ('PARTIAL_ADVANCE', 'Kısmi Peşin Ödeme'), ('LC', 'Akreditif'), ('DC', 'Belge Tahsilatı'), ('X_Y_NET_T', 'X/Y Net Vade'), ('TRADE_DISCOUNT', 'Ticari İskonto')], max_length=20, verbose_name='Vade Şartı'),
        ),
    ]
