# Generated by Django 5.2.4 on 2025-07-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_remove_historicalprocurementorder_invoice_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='invoice_date',
            field=models.DateField(null=True, verbose_name='Fatura Tebliğ Tarihi'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='invoice_date',
            field=models.DateField(null=True, verbose_name='Fatura Tebliğ Tarihi'),
        ),
    ]
