# Generated by Django 5.2.4 on 2025-07-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_historicalprocurementorder_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='payment_term',
            field=models.CharField(choices=[('NET_T', 'Net Vade'), ('DUE_ON_RECEIPT', 'Teslimde Ödeme'), ('CIA', 'Peşin Ödeme'), ('CWO', 'Siparişle Birlikte Ödeme'), ('COD', 'Teslimde Nakit'), ('CAD', 'Belge Karşılığı Ödeme'), ('EOM', 'Ay Sonu'), ('T_EOM', 'Ay sonundan T gün sonra'), ('PROX', 'Proksimo'), ('PARTIAL_ADVANCE', 'Kısmi Peşin Ödeme'), ('LC', 'Akreditif'), ('DC', 'Belge Tahsilatı'), ('X_Y_NET_T', 'X/Y Net Vade'), ('TRADE_DISCOUNT', 'Ticari İskonto')], max_length=20, verbose_name='Ödeme Koşulları'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='payment_term',
            field=models.CharField(choices=[('NET_T', 'Net Vade'), ('DUE_ON_RECEIPT', 'Teslimde Ödeme'), ('CIA', 'Peşin Ödeme'), ('CWO', 'Siparişle Birlikte Ödeme'), ('COD', 'Teslimde Nakit'), ('CAD', 'Belge Karşılığı Ödeme'), ('EOM', 'Ay Sonu'), ('T_EOM', 'Ay sonundan T gün sonra'), ('PROX', 'Proksimo'), ('PARTIAL_ADVANCE', 'Kısmi Peşin Ödeme'), ('LC', 'Akreditif'), ('DC', 'Belge Tahsilatı'), ('X_Y_NET_T', 'X/Y Net Vade'), ('TRADE_DISCOUNT', 'Ticari İskonto')], max_length=20, verbose_name='Ödeme Koşulları'),
        ),
    ]
