# Generated by Django 5.2.4 on 2025-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_alter_historicalprocurementorder_payment_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocurementorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='PO #no'),
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='po_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='PO #no'),
        ),
    ]
