# Generated by Django 5.2.4 on 2025-07-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_procurementorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementorder',
            options={'permissions': [('submit_procurementorder', 'Procurement officer approval'), ('approve_procurementorder', 'Procurement manager approval'), ('order_procurementorder', 'Procurement order permission'), ('cancel_procurementorder', 'Procurement order cancel permission'), ('bill_procurementorder', 'Can set invoice issuance date, also means invoice is approved')]},
        ),
    ]
