# Generated by Django 5.2.4 on 2025-07-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_procurementorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='due_discount_days',
            field=models.DurationField(null=True, verbose_name='Vade İskonto Günü'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='due_discount_days',
            field=models.DurationField(null=True, verbose_name='Vade İskonto Günü'),
        ),
    ]
