# Generated by Django 5.2.4 on 2025-07-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
        ('procurement', '0014_alter_historicalprocurementorder_due_discount_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementorderline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Malzeme'),
        ),
    ]
