# Generated by Django 5.2.4 on 2025-07-28 08:43

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_alter_procurementorderline_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='currency',
            field=core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='payment_term',
            field=models.CharField(choices=[('NET_T', 'Net Vade'), ('DUE_ON_RECEIPT', 'Teslimde Ödeme'), ('CIA', 'Peşin Ödeme'), ('COD', 'Teslimde Nakit'), ('EOM', 'Ay Sonu'), ('PARTIAL_ADVANCE', 'Kısmi Peşin Ödeme'), ('LC', 'Akreditif'), ('TRADE_DISCOUNT', 'Ticari İskonto')], max_length=20, verbose_name='Ödeme Koşulları'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='currency',
            field=core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='payment_term',
            field=models.CharField(choices=[('NET_T', 'Net Vade'), ('DUE_ON_RECEIPT', 'Teslimde Ödeme'), ('CIA', 'Peşin Ödeme'), ('COD', 'Teslimde Nakit'), ('EOM', 'Ay Sonu'), ('PARTIAL_ADVANCE', 'Kısmi Peşin Ödeme'), ('LC', 'Akreditif'), ('TRADE_DISCOUNT', 'Ticari İskonto')], max_length=20, verbose_name='Ödeme Koşulları'),
        ),
    ]
