# Generated by Django 5.2.4 on 2025-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_alter_historicalprocurementorder_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcurementInvoice',
        ),
    ]
