# Generated by Django 5.2.4 on 2025-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_delete_procurementinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocurementorder',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Fatura #no'),
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Fatura #no'),
        ),
    ]
