# Generated by Django 5.2.4 on 2025-08-01 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_historicalprocurementorder_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocurementorder',
            name='due_in_days',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Vade Günü'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='due_in_days',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Vade Günü'),
        ),
    ]
