# Generated by Django 5.2.4 on 2025-07-25 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
        ('procurement', '0015_alter_procurementorderline_material'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvariablecost',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Değişken Maliyet', 'verbose_name_plural': 'historical Değişken Maliyetler'},
        ),
        migrations.AlterModelOptions(
            name='variablecost',
            options={'verbose_name': 'Değişken Maliyet', 'verbose_name_plural': 'Değişken Maliyetler'},
        ),
        migrations.AddField(
            model_name='historicalvariablecost',
            name='procurement_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.procurementorder', verbose_name='Satınalma Siparişi'),
        ),
        migrations.AddField(
            model_name='historicalvariablecost',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='variablecost',
            name='procurement_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.procurementorder', verbose_name='Satınalma Siparişi'),
        ),
        migrations.AddField(
            model_name='variablecost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='variablecost',
            index=models.Index(fields=['material'], name='sales_varia_materia_fc8a13_idx'),
        ),
        migrations.AddIndex(
            model_name='variablecost',
            index=models.Index(fields=['procurement_order'], name='varcost_proc_order_idx'),
        ),
        migrations.AddIndex(
            model_name='variablecost',
            index=models.Index(fields=['user'], name='varcost_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='variablecost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('procurement_order__isnull', False), ('user__isnull', True)), models.Q(('procurement_order__isnull', True), ('user__isnull', False)), _connector='OR')), name='one_source_only'),
        ),
    ]
