# Generated by Django 5.2.4 on 2025-07-28 08:43

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
        ('procurement', '0016_alter_historicalprocurementorder_currency_and_more'),
        ('sales', '0002_alter_historicalvariablecost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variablecost',
            name='one_source_only',
        ),
        migrations.AddField(
            model_name='historicalvariablecost',
            name='bom',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bom.bom', verbose_name='Malzeme Listesi'),
        ),
        migrations.AddField(
            model_name='historicalvariablecost',
            name='currency',
            field=core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6),
        ),
        migrations.AddField(
            model_name='variablecost',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.bom', verbose_name='Malzeme Listesi'),
        ),
        migrations.AddField(
            model_name='variablecost',
            name='currency',
            field=core.fields.CurrencyField(choices=[('TRY', 'Türk Lirası'), ('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('RUB', 'Rus Rublesi')], default='TRY', max_length=6),
        ),
        migrations.AddIndex(
            model_name='variablecost',
            index=models.Index(fields=['bom'], name='varcost_bom_idx'),
        ),
        migrations.AddConstraint(
            model_name='variablecost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('bom__isnull', True), ('procurement_order__isnull', False), ('user__isnull', True)), models.Q(('bom__isnull', True), ('procurement_order__isnull', True), ('user__isnull', False)), models.Q(('bom__isnull', False), ('procurement_order__isnull', True), ('user__isnull', True)), _connector='OR')), name='one_source_only'),
        ),
    ]
