# Generated by Django 5.2.4 on 2025-07-30 08:56

import core.fields
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_deleted_company_deleted_by_cascade_and_more'),
        ('sales', '0004_salesorder_historicalsalesorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='material',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='quantity_sent',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='so',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='historicalsalesorder',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='material',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='quantity_sent',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='so',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='uom',
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrderLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Miktar')),
                ('uom', core.fields.UOMField(choices=[('ADT', 'Adet'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Mililitre'), ('M', 'Metre'), ('BOX', 'Koli'), ('PLT', 'Palet')], default='ADT', max_length=4, verbose_name='Birim')),
                ('quantity_sent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sevk Edilen Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birim Fiyat')),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vergi Oranı')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.material', verbose_name='Malzeme')),
                ('so', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesorder', verbose_name='Satış Emri')),
            ],
            options={
                'verbose_name': 'historical sales order line',
                'verbose_name_plural': 'historical sales order lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Miktar')),
                ('uom', core.fields.UOMField(choices=[('ADT', 'Adet'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Mililitre'), ('M', 'Metre'), ('BOX', 'Koli'), ('PLT', 'Palet')], default='ADT', max_length=4, verbose_name='Birim')),
                ('quantity_sent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=21, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sevk Edilen Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birim Fiyat')),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Vergi Oranı')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Malzeme')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Satış Emri')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
