# Generated by Django 5.2.4 on 2025-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_historicalsalesorder_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorderline',
            name='line_number',
            field=models.IntegerField(default=1, verbose_name='#'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='line_number',
            field=models.IntegerField(default='1', verbose_name='#'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Sunuldu'), ('approved', 'Onaylandı'), ('billed', 'Faturalandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Sunuldu'), ('approved', 'Onaylandı'), ('billed', 'Faturalandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
    ]
